### PR TITLE
[Fix] Force email to be lowercased.

### PR DESCRIPTION
**Pull request by emilieguth**
PATH=/compte

---
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/660)

### CODE REVIEW

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/660)* status: Missing an assignee or a reviewer, Unresolved discussions (src/components/pages/account.tsx:r1 line 250)

___
*[src/components/pages/account.tsx, line 250 at r1](https://reviewable.io/reviews/bayesimpact/ma-voie/660#-McTQU-HArNSCmJBsJ7s:-McTQU-HArNSCmJBsJ7t:b-efbf0q) ([raw file](https://github.com/bayesimpact/ma-voie/blob/a875959a670fdede4636b16ac3e59165efdc1cc8/src/components/pages/account.tsx#L250)):*
> ```XML
>     ...inputStyle,
>     borderColor: areErrorFields.email ? colors.RED_ERROR : colors.SILVER_THREE,
>     textTransform: 'lowercase',
> ```

This only changes the visual version of the text, but the value stored behind the scene is still uppercased.

Please fix the input itself (see how we did it in Bob)

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/660)* status: Missing an assignee or a reviewer

___
*[src/components/pages/account.tsx, line 250 at r1](https://reviewable.io/reviews/bayesimpact/ma-voie/660#-McTQU-HArNSCmJBsJ7s:-McToB9bAVc34jMO9yTu:b-896fix) ([raw file](https://github.com/bayesimpact/ma-voie/blob/a875959a670fdede4636b16ac3e59165efdc1cc8/src/components/pages/account.tsx#L250)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

This only changes the visual version of the text, but the value stored behind the scene is still uppercased.

Please fix the input itself (see how we did it in Bob)
</blockquote></details>

Done.

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/660#-:-McUA6h5EK0QPqfjzN5R:bnfp4nl)* status: Unresolved discussions (src/components/pages/account.tsx:r2 line 265)

___
*[src/components/pages/account.tsx, line 265 at r2](https://reviewable.io/reviews/bayesimpact/ma-voie/660#-McU9eXKBkHjyQG3xR7I:-McU9eXLEb-wd0MHe9vS:b-9n7kwj) ([raw file](https://github.com/bayesimpact/ma-voie/blob/e220e0c3c66e31a04cd6050ac06c606a710b7601/src/components/pages/account.tsx#L265)):*
> ```XML
>   }
> 
>   const onEmailChange = useCallback((email: string) => {
> ```

I have the feeling that this is the only change that is needed.

Can you try without the onChangeDelayMillisecs change if it works please?

I'm reluctant to add complexity.

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/660)* status: :shipit: complete! 0 of 2 files reviewed, 1 unresolved discussion

___
*[src/components/pages/account.tsx, line 265 at r2](https://reviewable.io/reviews/bayesimpact/ma-voie/660#-McU9eXKBkHjyQG3xR7I:-MciK93SBPoHT9zxcLYG:b-896fix) ([raw file](https://github.com/bayesimpact/ma-voie/blob/e220e0c3c66e31a04cd6050ac06c606a710b7601/src/components/pages/account.tsx#L265)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I have the feeling that this is the only change that is needed.

Can you try without the onChangeDelayMillisecs change if it works please?

I'm reluctant to add complexity.
</blockquote></details>

Done.

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/660)* status: Missing an assignee or a reviewer, Unresolved discussions (src/components/input.tsx:r3 line 7)

___
*[src/components/input.tsx, line 7 at r3](https://reviewable.io/reviews/bayesimpact/ma-voie/660#-MciMlR54QPpZJk5v6Uu:-MciMlR6CsuIhg9jPKoX:b-tptkxi) ([raw file](https://github.com/bayesimpact/ma-voie/blob/26e322a926357cb8762d89ac137e5381b06c3f18/src/components/input.tsx#L7)):*
> ```XML
>   extends Pick<HTMLInputElementProps, Exclude<keyof HTMLInputElementProps, 'onChange' | 'ref'>> {
>   onChange?: (inputValue: string) => void
>   onEdit?: (inputValue: string) => void
> ```

Please revert all changes in this file

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/660)* status: Missing an assignee or a reviewer

___
*[src/components/input.tsx, line 7 at r3](https://reviewable.io/reviews/bayesimpact/ma-voie/660#-MciMlR54QPpZJk5v6Uu:-MciQxFmDUAmh05svBFe:b-896fix) ([raw file](https://github.com/bayesimpact/ma-voie/blob/26e322a926357cb8762d89ac137e5381b06c3f18/src/components/input.tsx#L7)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please revert all changes in this file
</blockquote></details>

Done.

**Review by emilieguth — COMMENTED** [review]
+reviewer:@pcorpet 

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/660#-:-MciVbl0-DNTaIPcaz_h:b-4erzco)* status: :shipit: complete! 0 of 2 files reviewed, 2 unresolved discussions

**Pull request merged**
