### PR TITLE
[Fix] Prevent from unlogged users to access to logged pages only.

### PR DESCRIPTION
**Pull request by emilieguth**
PATH=/definition/partenaires

---
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/662)

### CODE REVIEW

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/662)* status: Missing an assignee or a reviewer, Unresolved discussions (src/components/pages/main.tsx:r1 line 82)

___
*[src/components/pages/main.tsx, line 82 at r1](https://reviewable.io/reviews/bayesimpact/ma-voie/662#-MciTvD_5l9W3booNkug:-MciTvD_5l9W3booNkuh:b-t55ouv) ([raw file](https://github.com/bayesimpact/ma-voie/blob/2dc99713ba1f4fef7ba6c585077dd6b13b2a9ec5/src/components/pages/main.tsx#L82)):*
> ```XML
>     <Route path={defineAndGetPath('ACCOUNT')} component={AccountPage} />
>     <Route path={defineAndGetPath('CONGRATULATIONS')} component={CongratulationsPage} />
>     {isConnected ? null : <Route path={defineAndGetPath('LOGIN')} component={LoginPage} />}
> ```

Let's use this pattern everywhere instead

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/662)* status: Missing an assignee or a reviewer

___
*[src/components/pages/main.tsx, line 82 at r1](https://reviewable.io/reviews/bayesimpact/ma-voie/662#-MciTvD_5l9W3booNkug:-MciURyRC1xm1v9HINwm:b-896fix) ([raw file](https://github.com/bayesimpact/ma-voie/blob/2dc99713ba1f4fef7ba6c585077dd6b13b2a9ec5/src/components/pages/main.tsx#L82)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Let's use this pattern everywhere instead
</blockquote></details>

Done.

**Review by emilieguth — COMMENTED** [review]
+reviewer:@pcorpet 

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/662#-:-MciVViYEUAwHvPf-MEu:b-4erzco)* status: LGTM missing from one of: pcorpet

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/662#-:-Mcnre3S9WyxzcztBz88:bnfp4nl)* status: Unresolved discussions (src/components/pages/main.tsx:r2 line 53)

___
*[src/components/pages/main.tsx, line 53 at r2](https://reviewable.io/reviews/bayesimpact/ma-voie/662#-McnrUIC7T44Ufq49ZQL:-McnrUIC7T44Ufq49ZQM:b-jl5pyy) ([raw file](https://github.com/bayesimpact/ma-voie/blob/82d2a04a914747a5f2c30eb1f88529c2b4bd8bff/src/components/pages/main.tsx#L53)):*
> ```XML
>   const {hash, pathname, search} = useLocation()
>   const userId = useUserId()
>   const isConnected = userId !== undefined
> ```

Do that in one line as you did in the other file

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/ma-voie/662)* status: :shipit: complete! 2 of 3 files reviewed, 1 unresolved discussion

___
*[src/components/pages/main.tsx, line 53 at r2](https://reviewable.io/reviews/bayesimpact/ma-voie/662#-McnrUIC7T44Ufq49ZQL:-Mcnsa_hBIWRsiPTeZVB:b-896fix) ([raw file](https://github.com/bayesimpact/ma-voie/blob/82d2a04a914747a5f2c30eb1f88529c2b4bd8bff/src/components/pages/main.tsx#L53)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Do that in one line as you did in the other file
</blockquote></details>

Done.

**Pull request merged**
